services:
    consul:
        image: "consul:latest"
        environment:
            - CONSUL_BIND_INTERFACE=eth0
        entrypoint: ["consul","agent","-server","-bootstrap-expect=1","-client","0.0.0.0","-data-dir","/consul-dir","-ui"]
        ports:
            - "8500:8500"
    grpc-kv1:
        image: "kv-server:latest"
        build:
            context: .
            dockerfile: "Dockerfile"
            target: "kv-server"
        environment:
            - PORT=8888
            - CONSUL_HTTP_ADDR=consul:8500
            - SERVICE_NAME=grpc-kv
            - SERVICE_ID=grpc-kv1
            - TAG=a
        ports:
            - "2000:8888"
        depends_on:
            - consul
    grpc-kv2:
        image: "kv-server:latest"
        build:
            context: .
            dockerfile: "Dockerfile"
            target: "kv-server"
        environment:
            - PORT=8888
            - CONSUL_HTTP_ADDR=consul:8500
            - SERVICE_NAME=grpc-kv
            - SERVICE_ID=grpc-kv2
            - TAG=b
        ports:
            - "2001:8888"
        depends_on:
            - consul
    grpc-kv3:
        image: "kv-server:latest"
        build:
            context: .
            dockerfile: "Dockerfile"
            target: "kv-server"
        environment:
            - PORT=8888
            - CONSUL_HTTP_ADDR=consul:8500
            - SERVICE_NAME=grpc-kv
            - SERVICE_ID=grpc-kv3
            - TAG=c
        ports:
            - "2002:8888"
        depends_on:
            - consul    
    kv-client:
        image: "kv-client:latest"
        build:
            context: .
            dockerfile: "Dockerfile"
            target: "kv-client"
        environment:
            - TARGET=consul://consul:8500/grpc-kv?interval=30s
        depends_on:
            - consul
            - grpc-kv1
            - grpc-kv2
            - grpc-kv3
    
